# version: "3.9"

services:
  # === APOLLO SERVER ==============================================
  apollo-server:
    build:
      context: ./apollo-server
      dockerfile: Dockerfile
    container_name: apollo-server
    hostname: apollo-server
    ports:
      - "4000:4000"    
    environment:
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - ELASTIC_APM_SECRET_TOKEN=secretoAPM
      - ELASTIC_APM_SERVICE_NAME=apollo-graphql
      - ELASTIC_APM_LOG_LEVEL=debug                  
    networks: [elastic]
    restart: on-failure

  # --- Nginx (Proxy inverso) ---
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    hostname: nginx-proxy
    ports:
      - "80:80"            
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - apollo-server
    networks:      
      - elastic

# === NETWORKS & VOLUMES ===========================================
networks:
  elastic:
    driver: bridge
