# version: "3.9"

services:
  # === CORE ELASTIC STACK =========================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node      # Nodo único
      - xpack.security.enabled=false    
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks: [elastic]

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on: [elasticsearch]
    networks: [elastic]

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.13.4
    container_name: apm-server
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
      - APM_SERVER_SECRET_TOKEN=secretoAPM      # Token que pondrás en tus agentes
    ports:
      - "8200:8200"
    depends_on: [elasticsearch, kibana]
    networks: [elastic]

  # --------------------- Logstash --------------------
  logstash:
    image: docker.elastic.co/logstash/logstash:8.13.4
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"    # Beats input
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
    depends_on: [elasticsearch]
    networks: [elastic]


# === NETWORKS & VOLUMES ===========================================
networks:
  elastic:
    driver: bridge

volumes:
  esdata:
    driver: local

