metricbeat.modules:
- module: system
  period: 10s
  metricsets:
    - cpu
    - memory
    - filesystem
    - diskio
    - load
  enabled: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "http://kibana:5601"
