# version: "3.9"

services:
  # === CORE ELASTIC STACK =========================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.17
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
      - discovery.type=single-node      # Nodo único
      - xpack.security.enabled=true    
      - ELASTIC_PASSWORD=changeme       
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks: [elastic]

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.17
    container_name: kibana
    hostname: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
    ports:
      - "5601:5601"
    depends_on: [elasticsearch]
    networks: [elastic]

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.17.17
    container_name: apm-server
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_HOST=http://kibana:5601
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - APM_SERVER_SECRET_TOKEN=secretoAPM      # Token que pondrás en tus agentes
    ports:
      - "8200:8200"
    volumes:
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    depends_on: [elasticsearch, kibana]
    networks: [elastic]

  # --------------------- Logstash --------------------
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.17
    container_name: logstash
    hostname: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"    # Beats input
    environment:
      - LS_JAVA_OPTS=-Xms256m -Xmx256m
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=changeme
      - xpack.monitoring.enabled=false   # Desactiva chequeo de licencia X-Pack      
    depends_on: [elasticsearch]
    networks: [elastic]


  # === APOLLO SERVER ==============================================
  apollo-server:
    build:
      context: ./apollo-server
      dockerfile: Dockerfile
    container_name: apollo-server
    hostname: apollo-server
    ports:
      - "4000:4000"    
    environment:
      - ELASTIC_APM_SERVER_URL=http://apm-server:8200
      - ELASTIC_APM_SECRET_TOKEN=secretoAPM
      - ELASTIC_APM_SERVICE_NAME=apollo-graphql
      - ELASTIC_APM_LOG_LEVEL=debug              
    depends_on: [kibana, elasticsearch, logstash]    
    networks: [elastic]
    restart: on-failure

  # --- Nginx (Proxy inverso) ---
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    hostname: nginx-proxy
    ports:
      - "80:80"            
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - apollo-server
    networks:      
      - elastic

# === NETWORKS & VOLUMES ===========================================
networks:
  elastic:
    driver: bridge

volumes:
  esdata:
    driver: local

