filebeat.inputs:
  - type: log                  # Tipo de entrada: lectura de archivos
    id: container-logs                # Identificador de la entrada
    paths:
      - /var/log/*.log                # Logs del sistema dentro del contenedor
    ignore_older: 72h                 # Ignora archivos no modificados en 72h    

# ========== SALIDA (Logstash) ======================================
output.logstash:
  hosts: ["logstash:5044"] # Dirección de Logstash 
  # username: "elastic"          # Usuario para autenticación
  # password: "changeme"        # Contraseña para autenticación

# output.elasticsearch:
#   hosts: ["http://elasticsearch:9200"]  # Dirección de Elasticsearch
#   username: "elastic"                   # Usuario para autenticación
#   password: "changeme"                  # Contraseña para autenticación

# ========== INTEGRACIÓN CON KIBANA ================================
setup.kibana:
  host: "http://kibana:5601"                 # Dirección de Kibana
  username: "elastic"                          # Usuario para autenticación
  password: "changeme"                        # Contraseña para autenticación

# Configuración de plantillas y dashboards
setup.template.enabled: true
setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true


# ========== PROCESADORES ==========================================
processors:
  - add_host_metadata: ~               # Añade metadatos del host
  - add_docker_metadata: ~             # Añade metadatos de Docker
  - add_cloud_metadata: ~              # Añade metadatos de cloud

# ========== MÓDULOS DE FILEBEAT ===================================
filebeat.modules:
  - module: system                    # Módulo para logs del sistema
    syslog:
      enabled: true                   # Habilita recolección de syslog
    auth:
      enabled: true                   # Habilita recolección de logs de autenticación

# Fin del archivo
